Update action.yml

diff --git a/quality-gate/action.yml b/quality-gate/action.yml
--- a/quality-gate/action.yml
+++ b/quality-gate/action.yml
@@ -23,22 +23,65 @@ runs:
   steps:
     - name: Script
       if: ${{ inputs.ENABLE_QUALITY_GATE == 'true' }}
+      id: csv_reporter
       shell: pwsh
       run: |        
         Write-Host "IMPORTING A CSV FILE IN POWERSHELL"
-        $CSV_FILE = Import-Csv -Path "${{ inputs.ALLURE_BEHAVIORS_CSV }}"
-        Write-Host "THE FILE IS IMPORTED USING CMDLET" 
-        Write-host "FAILED Test Cases: $CSV_FILE._$.FAILED"
-        Write-host "PASSED Test Cases: $CSV_FILE._$.PASSED" 
-        Write-host "SKIPPED Test Cases: $CSV_FILE._$.SKIPPED"
-        Write-host "UNKNOWN Test Cases: $CSV_FILE._$.UNKNOWN"
-        echo "FAILED_TC=[int]$CSV_FILE.FAILED" >> $Env.GITHUB_ENV
-        echo "PASSED_TC=[int]$CSV_FILE.PASSED" >> $Env.GITHUB_ENV
-        echo "SKIPPED_TC=[int]$CSV_FILE.SKIPPED" >> $Env.GITHUB_ENV
-        echo "UNKNOWN_TC=[int]$CSV_FILE.UNKNOWN" >> $Env.GITHUB_ENV
-        $TOTAL_TC = [int]$FAILED_TC + [int]$PASSED_TC + [int]$SKIPPED_TC + [int]$UNKNOWN_TC
-        "TOTAL_TC = [int]$TOTAL_TC" >> $Env.GITHUB_ENV
-        Write-Host "CALCULATING PASS PERCENTAGE ACHIEVED"
-        $PASS_PERCENTAGE = $FAILED / $TOTAL_TC
-        Write-Host $PASS_PERCENTAGE
+        $CSV_PATH = Import-Csv -Path "${{ inputs.ALLURE_BEHAVIORS_CSV }}"
+        PASSED_TESTS = Get-Content $CSV_PATH | ConvertFrom-Csv | Measure-Object "PASSED" -Sum
+        FAILED_TESTS = Get-Content $CSV_PATH | ConvertFrom-Csv | Measure-Object "FAILED" -Sum
+        SKIPPED_TESTS = Get-Content $CSV_PATH | ConvertFrom-Csv | Measure-Object "SKIPPED" -Sum
+        UNKNOWN_TESTS = Get-Content $CSV_PATH | ConvertFrom-Csv | Measure-Object "UNKNOWN" -Sum        
+        echo "FAILED_TESTS=[int]$FAILED_TESTS" >> $Env.GITHUB_ENV
+        echo "PASSED_TESTS=[int]$PASSED_TESTS" >> $Env.GITHUB_ENV
+        echo "SKIPPED_TESTS=[int]$SKIPPED_TESTS" >> $Env.GITHUB_ENV
+        echo "UNKNOWN_TESTS=[int]$UNKNOWN_TESTS" >> $Env.GITHUB_ENV
+        echo "##[set-output name=PASSED_TESTS;]${PASSED_TESTS}"
+        echo "##[set-output name=FAILED_TESTS;]${FAILED_TESTS}"
+        echo "##[set-output name=SKIPPED_TESTS;]${SKIPPED_TESTS}"
+        echo "##[set-output name=UNKNOWN_TESTS;]${UNKNOWN_TESTS}"
         
+    - name: Gate
+      if: ${{ inputs.ENABLE_QUALITY_GATE == 'true' }}
+      shell: pwsh
+      run: |
+        $MIN_PERCENTAGE = [int]${{ inputs.MINIMUM_PASS_PERCENTAGE }}
+        echo "Minimum Percentage required is : $MIN_PERCENTAGE "
+        echo "Minimum Percentage Required: $MIN_PERCENTAGE" >> $GITHUB_STEP_SUMMARY
+        $PASSED_TESTS = [int]${{ env.PASSED_TESTS }}
+        Write-Output "Passed Tests: $PASSED_TESTS"
+        echo "Passed Tests: $PASSED_TESTS" >> $GITHUB_STEP_SUMMARY
+        $FAILED_TESTS = [int]${{ env.FAILED_TESTS }}
+        echo "Failed Tests: $PASSED_TESTS" >> $GITHUB_STEP_SUMMARY
+        Write-Output "Failed Tests: $FAILED_TESTS"
+        $SKIPPED_TESTS = [int]${{ env.SKIPPED_TESTS }}
+        echo "Skipped Tests: $SKIPPED_TESTS" >> $GITHUB_STEP_SUMMARY
+        Write-Output "Skipped Tests: $SKIPPED_TESTS"
+        echo "Total Tests: $SKIPPED_TESTS" >> $GITHUB_STEP_SUMMARY
+        $UNKNOWN_TESTS = [int]${{ env.UNKNOWN_TESTS }}
+        echo "Unknown Tests: $UNKNOWN_TESTS" >> $GITHUB_STEP_SUMMARY
+        Write-Output "Unkown Tests: $UNKNOWN_TESTS"        
+        $TOTAL_TESTS = $PASSED_TESTS + $FAILED_TESTS + $SKIPPED_TESTS + $UNKNOWN_TESTS
+        Write-Output "Total Tests: $TOTAL_TESTS"
+        if ( ($FAILED_TESTS + $SKIPPED_TESTS) -ne 0 ) {
+                  $PASS_PERCENTAGE_INT = ($PASSED_TESTS / $TOTAL_TESTS ) * 100
+                  $PASS_PERCENTAGE_STRING = ($PASSED_TESTS / $TOTAL_TESTS ).tostring("P")
+          }
+          else
+          {
+            Write-Output "None of the tests failed"
+            exit 0
+          }
+        if ( $PASS_PERCENTAGE_INT -ge $MIN_PERCENTAGE ) {
+          Write-Output "Achieved Pass Percentage of $PASS_PERCENTAGE_STRING, which is greater than or equal to Minium Percentage Set: $MIN_PERCENTAGE "
+          exit 0
+        }
+        else {
+          Write-Output "Minimum Pass Percentage Required is $MIN_PERCENTAGE, But Achieved is $PASS_PERCENTAGE_STRING"
+          exit 1
+        }
+        echo "Pass Percentage Achieved: $PASS_PERCENTAGE_STRING" >> $GITHUB_STEP_SUMMARY
+
+
+
+
